"""Shared Excel writer for Canva Bulk Create image fields.

Canva reads images from floating pictures anchored to spreadsheet cells.  A CSV
that merely contains a local PNG filename cannot populate an image frame.
"""
from __future__ import annotations

import os
from collections.abc import Iterable, Sequence
from typing import Any


def write_bulk_excel(
    out_path: str,
    rows: Sequence[dict[str, Any]],
    text_columns: Sequence[str],
    image_columns: Sequence[str],
    *,
    max_rows: int = 0,
) -> list[str]:
    """Create one or more Canva-compatible workbooks with embedded images."""
    import xlsxwriter

    def write_part(path: str, part_rows: Iterable[dict[str, Any]]) -> str:
        workbook = xlsxwriter.Workbook(path)
        sheet = workbook.add_worksheet("Bulk Create")
        headers = [*text_columns, *image_columns]
        for column, header in enumerate(headers):
            sheet.write(0, column, header)
        for row_index, row in enumerate(part_rows, start=1):
            for column, name in enumerate(text_columns):
                sheet.write(row_index, column, row.get(name, ""))
            sheet.set_row(row_index, 150)
            for offset, name in enumerate(image_columns):
                column = len(text_columns) + offset
                image_path = row.get(name)
                if image_path and os.path.isfile(image_path):
                    sheet.insert_image(row_index, column, image_path, {
                        "x_scale": 0.09,
                        "y_scale": 0.09,
                        "positioning": 1,
                        "x_offset": 5,
                        "y_offset": 5,
                    })
                else:
                    sheet.write(row_index, column, "No image")
        for column in range(len(text_columns), len(headers)):
            sheet.set_column(column, column, 30)
        workbook.close()
        return path

    if max_rows <= 0 or len(rows) <= max_rows:
        return [write_part(out_path, rows)]

    base, ext = os.path.splitext(out_path)
    pad_len = 3 if len(rows) >= 100 else 2
    part_files = []
    for part, start in enumerate(range(0, len(rows), max_rows), start=1):
        end = min(len(rows), start + max_rows)
        part_name = f"{base}_batch_{part:02d}_pages_{start+1:0{pad_len}d}-{end:0{pad_len}d}{ext}"
        part_files.append(write_part(part_name, rows[start:end]))
    return part_files


def get_canva_instructions_text(num_batches: int, total_pages: int, batch_size: int, title: str = "Puzzle Book") -> str:
    """Generate friendly instructions for Canva Bulk Create batch imports."""
    batch_lines = []
    for i in range(num_batches):
        s = i * batch_size + 1
        e = min(total_pages, (i + 1) * batch_size)
        batch_lines.append(f"  • Batch {i+1:02d}: Pages {s} to {e}")
    batches_str = "\n".join(batch_lines)

    return f"""===================================================================
CANVA BULK CREATE - BATCH IMPORT GUIDE
{title} ({total_pages} Total Pages)
===================================================================

WHY ARE THERE MULTIPLE FILES?
Canva has a strict design limit (typically 100 pages per project).
Importing 300+ pages all at once causes Canva to limit generation or fail.

Your book has been automatically divided into {num_batches} ordered,
ready-to-use batches of up to {batch_size} pages each:

INCLUDED BATCH FILES IN THIS ZIP:
{batches_str}

HOW TO USE IN CANVA:
1. Open Canva and create your page layout (e.g. 8.5 x 11 in).
2. Go to Canva Apps -> Search for "Bulk Create".
3. Click "Upload CSV / Excel" and select:
   Batch 01 (e.g. *_batch_01_pages_001-100.xlsx).
4. Right-click elements on your template to connect data:
   - Connect Title -> {{title}} (or {{puzzle_1_title}})
   - Connect Image Frame -> {{grid_image}} (or {{grid_image_1}})
   - Connect Solution Frame -> {{solution_image}} (if solutions included)
   - Connect Date -> {{date}} (if dates enabled)
5. Click "Continue" -> "Generate Pages". Canva generates your first {min(total_pages, batch_size)} pages!
6. For the next batch, duplicate your Canva design template,
   upload Batch 02, and generate the next batch of pages.
7. Combine the generated PDFs with any PDF merger tool, or use the
   instant 1-click "KDP Interior PDF" directly from the Studio!
===================================================================
Generated by KDP Activity Studio
===================================================================
"""


def package_canva_batches_zip(batch_files: Sequence[str], zip_out_path: str, instructions_text: str = "") -> str:
    """Package multiple Canva batch Excel files into a cleanly named ZIP bundle."""
    import zipfile
    with zipfile.ZipFile(zip_out_path, "w", zipfile.ZIP_DEFLATED) as z:
        for f in batch_files:
            z.write(f, os.path.basename(f))
        if instructions_text:
            z.writestr("CANVA_BULK_CREATE_INSTRUCTIONS.txt", instructions_text)
    return zip_out_path

